#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$app = require __DIR__.'/bootstrap/app.php';

$app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);
